### ISSUE TITLE
showInformationMessage too intrusive

### ISSUE THREAD

**Issue by cerk** [ionide/ionide-vscode-fake#13]
I have been using the ionide-vscode-fake extension for a few days now and it feels like the showInformationMessage command is too intrusive during the build process. There are three instances of the command in src/fake.fs:

```
window.Globals.showInformationMessageOverload2 ("Build started", "Open")
```

```
window.Globals.showInformationMessage "Build completed" |> ignore
```

```
window.Globals.showErrorMessage "Build failed" |> ignore
```

It seems like the "Build failed" message could stay as a showErrorMessage, but the other two might be better suited to be shown on the status bar. The reason for this is that currently I have to press the "Close" button on the two information messages every time I build. They just sit there and never go away. I do not feel like the "Build started" and "Build completed" messages are important enough for me to have to close them every time. Also, it seems like the "Open" button for "Build started" is redundant because the FAKE output window opens automatically.

Thanks for considering. If you think this idea has any merit and If you want me to try and code the changes up, I will but I am not very familiar with vscode extensions currently.

**Comment by bbhh** [comment]
I'm absolutely loving this extension, but this is a large annoyance because it covers up the top of my file editing pane and requires unnecessary clicks to dismiss them.

It looks like all we need to do, building on @cerk's suggestion above, is to replace the `window.Globals.{showInformationMessageOverload2,showInformationMessage,showErrorMessage}` calls with `vscode.window.setStatusBarMessage` instead (see relevant vscode commands [here](https://code.visualstudio.com/docs/extensionAPI/vscode-api)).

I tried making this change in the F#/FunScript code but had difficulty getting the FAKE project to build properly due to dependencies, and don't have time now to make it work. So for the time being, I just edited my local transpiled JS file (%USERPROFILE%\.vscode\extensions\Ionide.Ionide-FAKE-1.1.0\fake.js) and made the replacements myself, and it works nicely, only non-intrusively showing the _Build started/completed/failed_ messages in the status bar. Here's the diff:

```
277,287c277
<       var ignored0 = Promise__success$String__Unit_String_Unit_((function(n)
<       {
<         if ((n == "Open"))
<         {
<           return (FakeService__outputChannel.show(2));
<         }
<         else
<         {
<           ;
<         };
<       }), Promise__toPromise$String_String((vscode.window.showInformationMessage("Build started", "Open"))));

---
>       vscode.window.setStatusBarMessage("Build started");
313c303
<           var __ignored0 = (vscode.window.showInformationMessage("Build completed"));
---
>           var __ignored0 = (vscode.window.setStatusBarMessage("Build completed"));
317c307
<           var ___ignored0 = (vscode.window.showErrorMessage("Build failed"));
---
>           var ___ignored0 = (vscode.window.setStatusBarMessage("Build failed"));
```

**Comment by bbhh** [comment]
Thank you! :)
